reprompt_strategy:
  task: Analyze failed or ineffective actions from the plant_operator and suggest a modified plan.
  description: >
    When the validation agent detects that an action was not successfully executed (e.g., flow obstruction, incorrect valve status, or insufficient pump power), this agent receives the fault context and current system state.

    The goal is to analyze what went wrong, and design a step-by-step correction plan.

    **Current State:**
      - The level of tank B201 is {B201_level}m 
      - The level of tank B202 is {B202_level}m 
      - The level of tank B203 is {B203_level}m 
      - The level of tank B204 is {B204_level}m 
      - The valve_in0 is {valve_in0} 
      - The valve_in1 is {valve_in1}
      - The valve_in2 is {valve_in2}
      - The valve_pump_tank_B201 is {valve_pump_tank_B201} 
      - The valve_pump_tank_B202 is {valve_pump_tank_B202} 
      - The valve_pump_tank_B203 is {valve_pump_tank_B203} 
      - The valve_pump_tank_B204 is {valve_pump_tank_B204} 
      - The valve_out is {valve_out}
      - The pump power is {pump_power} times of max pump power of 750W.
    
    **System Specifications:**
      - Valves B201, B202, B203 and B204 are solenoid valves that is on or off only. 
      - The pump power can be adjusted between 0 and 1 (0 to 750W).
      - The pump is speed-controlled via an input shaft speed N (rpm), with a nominal speed of 166.43 rpm. The agent can vary the input speed to increase or decrease flow.
      - The pump follows a quadratic head vs. flow rate relationship. At higher speeds, the pump can deliver greater head and flow. The flow direction is fixed due to a built-in check valve (no flow reversal allowed). 
      
    - Validation agent has flagged an issue with the current operation. 
      - The issue flagged is {issue_flagged} (e.g., flow obstruction, incorrect valve status, or insufficient pump power).
    - Fault detected by monitoring agent is {fault_detected} (e.g., clogging anomaly in the line connecting tanks B201, B202, and B203 to B204).

    **Actuators:**
    - The agent can manipulate the following actuators:
      - **Valves:** valve_in0, valve_in1, valve_in2, valve_pump_tank_B201, valve_pump_tank_B202, valve_pump_tank_B203, valve_pump_tank_B204, valve_out
      - **Pump Power:** Adjust the pump power between 0 and 1 (0 to 750W).

    **What to do:**
    - Analyze the current state and detected faults and manipulate the acutators to overcome the issues.

    **Output Format:**
    - List of new valve/pump commands.
    - Reasoning for each change.
    - Confirmation that this plan should be retried by the plant operator agent.

  agent: reprompt_agent
  expected_output: >
    Suggested corrective actions with detailed reasoning. This should be relayed back to the plant_operator agent to retry the operation effectively.
