plant_operation:
    task: To sequentially fill and empty tanks B201, B202 and B203 to mix liquids in tank B204.
    description: >
      Follow these rules:
      - Only act within the current state. Do not anticipate future steps.
      - Transitions between states follow a strict finite-state machine. You must only advance if the transition condition is met.
      - If the condition for transition is not met, continue current operations or return no new actions.
      - Do not guess. Do not skip states.

      **Current State:**
      - The level of tank B201 is {B201_level}m 
      - The level of tank B202 is {B202_level}m 
      - The level of tank B203 is {B203_level}m 
      - The level of tank B204 is {B204_level}m 
      - The valve_in0 is {valve_in0} 
      - The valve_in1 is {valve_in1}
      - The valve_in2 is {valve_in2}
      - The valve_pump_tank_B201 is {valve_pump_tank_B201} 
      - The valve_pump_tank_B202 is {valve_pump_tank_B202} 
      - The valve_pump_tank_B203 is {valve_pump_tank_B203} 
      - The valve_pump_tank_B204 is {valve_pump_tank_B204} 
      - The valve_out is {valve_out}

      **Plant Structure:**
      - Understand the connections and flow paths between tanks and valves. The P&ID diagram is represented as follows in a graph format:
        {plant_structure}

      **State Graph:**
      - The state graph represents the sequence of operations in the plant. It is a directed graph where each node represents a state and each edge represents a transition condition between states as follows:
        fill_tank_B201 → fill_tank_B202 → fill_tank_B203 → drain_tank_B201 → drain_tank_B202 → drain_tank_B203 → end
        
      - Below are the transitions and conditions:
        - fill_tank_B201 → fill_tank_B202 if B201 > 0.032m
        - fill_tank_B202 → fill_tank_B203 if B202 > 0.032m
        - fill_tank_B203 → drain_tank_B201 if B203 > 0.032m
        - drain_tank_B201 → drain_tank_B202 if B201 < 0.022m
        - drain_tank_B202 → drain_tank_B203 if B202 < 0.022m
        - drain_tank_B203 → end if B203 < 0.022m

      - Think of what valves and pumps are required to be open or closed based on the current state.

      **Action Process:**
      - Please follow the state graph strictly. For each state transition, check if the conditions are met.
      - If the condition is met, perform the action to transition to the next state. If not, return "no action" and maintain the current state.

      **Suggested Action for Agent:**
      {reprompting_suggestions}

      **Example Action:**
      - If **B201** is empty, the agent should return: `valve_pump_tank_B201 - close`.

    agent: plant_operator
    expected_output: >
      Valve operation required to successfully fill and empty the liquid, along with a clear reasoning process for each action and thought process.